language: python
python: 3.8
install:
    - pip3 install -r requirements.txt
script:
    - sphinx-build -b html -a -q -w warnings . _build
    - |
      if [ $(wc -c <warnings) -ne 0 ]; then
          echo -e "\\e[31mERROR: failing build due to build warnings (see above)\\e[0m"
          false
      fi
